### ISSUE TITLE
No mention of "sort_by" argument of get_grades() in README

### ISSUE THREAD

**Issue by FancyBaguette** [Poroknights/librus-apix#14]
In the README, the usage of get_grades is shown as follows:
```python
from librus_apix.grades import get_grades

grades, average_grades = get_grades(token)

for mark in grades["Mathematics"]:
    print(mark.grade)
```

Running this code results in `TypeError: get_grades() missing 1 required positional argument: 'sort_by'`

**Comment by Poroknights** [comment]
The sort_by argument is for getting new grades or grades since last login. I actually forgot about it when writing the README. I will set the sort_by to get all grades by default and update the README file.
